

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	return (
		
			<html lang="en">
			<body className={inter.className}>
				<div className={`flex  w-full bg-[#FAFAFA] dark:bg-dark-100`}>
				<div className="hidden md:flex  md:w-[8vw] min-w-[80px] xl:w-[16vw] 2xl:w-[20vw]">
					<Sidebar/>
				</div>
				<main className="main h-[100%] xl:w-[84vw] 2xl:w-[80vw]">
					<Header type="layout"/>
					{children}
					
				</main>
			</div>
			</body>
		</html>
		
	);
}
